### ISSUE TITLE
Add ability to revoke approval permissions to CEP-47

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/casper-nft-cep47#38]
@RitaMAllenCA commented on [Thu Feb 23 2023](https://github.com/casper-ecosystem/cep-78-enhanced-nft/issues/173)

Since we can assign this permission, we need the revocation to be possible as well.  

---

@RitaMAllenCA commented on [Thu Feb 23 2023](https://github.com/casper-ecosystem/cep-78-enhanced-nft/issues/173#issuecomment-1442295350)

@darthsiroftardis @gRoussac please provide an estimate once you've had a chance to review.

**Comment by cspramit** [comment]
@gRoussac @darthsiroftardis friendly reminder to provide estimates

**Comment by deuszex** [comment]
@cspramit This is cep47, we do not actively support cep47. If someone wants to do a revoke on cep47, they can call approve again with a different approval set, since it is an "overwrite" scheme and the newer version completely overwrites the old one.
@RitaMAllenCA ^ based on the above this is not a cep-78 release, that is a completely different ticket done by Gregory
